### ISSUE TITLE
Webhooks: Integrate external back office services to automate custom processing of credential presentation and verification activities

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#14]
Acceptance Test (Manual w/ VC in Credential Application)

1. Create a DID (did:key or did:web) for the Issuer.
2. Create a DID (did:key or did:web) for the Alice applicant.
3. Configure a webhook that is to be used for automatically responding to Credential Applications.
4. Create a schema to be used in the Credential Manifest using the Issuer’s DID.
5. Create a Verifiable Credential to be used in Credential Application using the Issuer’s DID.
6. Create a Credential Manifest using the Issuer's DID.
7. Submit a Credential Application using Alice’s DID.
8. Confirm that the Credential Application is in the ‘Pending’ state.
9. Triggered by the Credential Application event, Webhook to call external service, which in the happy path case will Approve the application.
10. Confirm that the Credential Application is in the ‘Approved’ state.
11. Retrieve the Credential Response and verify it is valid.

# tasks
- [ ] acceptance test listed above
- [ ] polling example and documentation
- [ ] documentation in the README

**Comment by nitro-neal** [comment]
https://github.com/TBD54566975/ssi-service/pull/418
