### ISSUE TITLE
Implement OIDC 4 VC Issuance

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#351]
https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html

# tasks
- [ ] [Setup a simple OAuth2 authN server](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-oauth-20)
- [ ] [Credential offer endpoint](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-offer-endpoint)
- [ ] [authZ endpoint](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-authorization-endpoint)
- [ ] [Token endpoint](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-token-endpoint)
- [ ] [Credential endpoint](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-endpoint)
- [ ] _optional_ [Batch credential](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-batch-credential-endpoint)
- [ ] [Deferred credential](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-pre-authorized-code-flow-2)

# tests
- [ ] [Integration test for authZ code flow](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-authorization-code-flow)
- [ ] [Integration test for pre-authZ code flow](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-pre-authorized-code-flow)
