### ISSUE TITLE
Implement OIDC 4 VP

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-service#352]
https://openid.net/specs/openid-4-verifiable-presentations-1_0.html

# tasks
- [ ] [Create Oauth Authorization Request functionality](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-authorization-request)
  This might belong inside the SDK. Make it easy for it to be renders via a QR code (see https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-5.5)
- [ ] Expose client_metadata
The verifier (i.e. ssi-service) must make client metadata available for wallets. See https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-verifier-metadata-client-me for mechanisms on how to communicate it, an what data should be in it. Ensure that client metadata has vp_formats.
- [ ] Endpoint for accepting `vp_token` and `presentation_submission`
This endpoint should be included as the redirect_uri in the oauth authorization request. The response_mode should be set to direct_post.jwt. The encryption should be done using jwks from the client_metadata. The signing should use the wallet's private key (i.e. the DID's key of the wallet). Encryption and signing should follow the spec in https://openid.net/specs/oauth-v2-jarm-final.html#name-signing-and-encryption. The endpoint should accept a single response parameter. More details in https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-response

# tests
- [ ] Integration Test for VP flow
